# React App Deployment Pipeline

trigger:
  - main

pool:
  vmImage: 'windows-latest'

# define variables to use during the build
variables:
  projectFolder: '.'
  buildOutputFolder: 'dist'

# installing node.js
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # Run the yarn install
  - script: |
      yarn install

  # Download secure file from azure library
  - task: DownloadSecureFile@1
    inputs:
      secureFile: '.env.development'

  # Copy the .env file
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: '**/*.env.development'
      targetFolder: '$(projectFolder)'
      cleanTargetFolder: false

  # Run the yarn build
  - script: |
      yarn build --mode development

  # Download secure file from azure library
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'web.config'

  # Copy the web.config file
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: '**/*web.config'
      targetFolder: '$(buildOutputFolder)'
      cleanTargetFolder: false

  # Copy all the files to the staging directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildOutputFolder)'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      cleanTargetFolder: true

  # Archive all the files into a zip file for publishing
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      includeRootFolder: false

  # Publish the zip file
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
